export const ROLES = {
  ADMIN: "admin",
  MEMBER: "member",
  ADVISOR: "advisor",
  TRUSTEE: "trustee",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const APP_ROLES: Record<string, Role[]> = {
  HOME: [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE],
  FAMILY: [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE],
  DOCUMENTS: [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE],
  LIBRARY: [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE],
  LESSONS: [ROLES.ADMIN, ROLES.MEMBER],
  SIGNALS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  SIMULATIONS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  PROFESSIONALS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  GOVERNANCE: [ROLES.ADMIN],
  SETTINGS: [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE],
};
