export const ROLES = {
  ADMIN: "admin",
  MEMBER: "member",
  ADVISOR: "advisor",
  TRUSTEE: "trustee",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

const ALL_ROLES: Role[] = [ROLES.ADMIN, ROLES.MEMBER, ROLES.ADVISOR, ROLES.TRUSTEE];

export const APP_ROLES: Record<string, Role[]> = {
  HOME: ALL_ROLES,
  MESSAGES: ALL_ROLES,
  EVENTS: ALL_ROLES,
  ASSETS: ALL_ROLES,
  SIGNALS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  SIMULATIONS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  DOCUMENTS: ALL_ROLES,
  LESSONS: [ROLES.ADMIN, ROLES.MEMBER],
  FAMILY: ALL_ROLES,
  PROFESSIONALS: [ROLES.ADMIN, ROLES.ADVISOR, ROLES.TRUSTEE],
  LEGACY: ALL_ROLES,
  SETTINGS: ALL_ROLES,
};
